### ISSUE TITLE
Can "models.rar" be opened?

### ISSUE THREAD

**Issue by littleforce163** [guanshuicheng/invoice#1]
I've download "models.rar" but can not open it. Any one fit the same problem?

**Comment by guanshuicheng** [comment]
I re-uploaded the model and provided the download link. There is no need to unzip it. You can download it again

**Comment by guanshuicheng** [comment]
> I've download "models.rar" but can not open it. Any one fit the same problem?

I re-uploaded the model and provided the download link. There is no need to unzip it. You can download it again

**Comment by littleforce163** [comment]
It's fixed.Thanks.
