### ISSUE TITLE
数据集

### ISSUE THREAD

**Issue by lyouthzzz** [guanshuicheng/invoice#10]
可以提供部分数据集吗？想train一下代码。谢谢

**Comment by WanghuiRs** [comment]
这个代码应该怎么train呀

**Comment by helloworld1973** [comment]
请问可以开放训练数据集和方法么

**Comment by JinMana** [comment]
同求数据集

**Comment by Wangjii** [comment]
同求训练方法

**Comment by guanshuicheng** [comment]
检测和识别的训练脚本在chineseocr中已经提供，根据自己的场景稍加修改就可以了，发票数据由于涉及隐私，无授权无法开放，可以通过模板生成一部分，另外拍摄一小部分真实场景下的发票数据进行标注，数据增强一部分，基本可以达到训练的需求

**Comment by DuckJ** [comment]
@guanshuicheng 请问能提供一下生成增值税发票的思路和脚本吗
