### ISSUE TITLE
识别区域是如何训练的

### ISSUE THREAD

**Issue by helloworld1973** [guanshuicheng/invoice#13]
感觉作者的文字检测中，相比于Chines OCR 还包含了识别区域的检测，请问作者如何标注和训练识别区域的，谢谢

**Comment by helloworld1973** [comment]
感觉作者的文字检测中，相比于Chines OCR 还包含了识别区域的检测，请问作者如何标注和训练识别区域的，谢谢

**Comment by guanshuicheng** [comment]
检测部分的数据标注可以用这个https://github.com/tzutalin/labelImg，识别部分的数据可以根据场景的需求大批量生成

**Comment by guanshuicheng** [comment]
> 感觉作者的文字检测中，相比于Chines OCR 还包含了识别区域的检测，请问作者如何标注和训练识别区域的，谢谢

检测部分的数据标注可以用这个https://github.com/tzutalin/labelImg，
识别部分的数据可以根据场景的需求大批量生成
