### ISSUE TITLE
Allocation of 411041792 exceeds 10% of system memory.

### ISSUE THREAD

**Issue by chneone** [guanshuicheng/invoice#15]
how to deal with the problem? the memory is too smaller? I use 8G RAM for  win10 systerm

**Comment by guanshuicheng** [comment]
> how to deal with the problem? the memory is too smaller? I use 8G RAM for win10 systerm

You can turn off the model of text image orientation correction, or set the GPU to elastic: config.gpu_options.allow_growth = True, because I default set to 0.3 GPU memory
