### ISSUE TITLE
开发者是否愿意收费进行二次开发呢？

### ISSUE THREAD

**Issue by Casablanca94** [guanshuicheng/invoice#16]
您好，我们需要票据识别软件，但不具备这个开发能力，不知开发者是否有意向二次开发呢，我们愿意付出相应的酬劳。

**Comment by Casablanca94** [comment]
希望获得您的联系方式，这是我的邮件地址nightingale2whm@gmail.com。

**Comment by guanshuicheng** [comment]
感谢，开发者表示对coding感兴趣，对钱不感兴趣。

**Comment by Casablanca94** [comment]
感谢您的回复。
