### ISSUE TITLE
请求参数错误

### ISSUE THREAD

**Issue by xiaoliuit** [guanshuicheng/invoice#17]
[请求的时候不是直接上传图片吗？请求参数是？]

返回结果是：
{
    "FileName": {},
    "code": 101,
    "data": {},
    "message": "请求参数错误",
    "ocrIdentifyTime": {}
}

**Comment by xiaoliuit** [comment]
我已经解决，请求时，Headers不能有任何key-value

**Comment by FrankYuu** [comment]
你好，请问请求参数需要填什么？

**Comment by guanshuicheng** [comment]
请求参数key是“file”，value你可以直接上传图片，postman会自行编码图片，详细情况可以阅读app.py中的代码

**Comment by FrankYuu** [comment]
好的，谢谢您的回复！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"John"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月18日(星期四) 上午9:31
收件人:&nbsp;"guanshuicheng/invoice"<invoice@noreply.github.com&gt;;
抄送:&nbsp;"太原理工大学俞承言"<695807870@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [guanshuicheng/invoice] 请求参数错误 (#17)





 
请求参数key是“file”，value你可以直接上传图片，postman会自行编码图片，详细情况可以阅读app.py中的代码
