### ISSUE TITLE
服务调用问题

### ISSUE THREAD

**Issue by 15926273249** [guanshuicheng/invoice#18]
* Serving Flask app "app" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:11111/ (Press CTRL+C to quit)

在浏览器上 http://0.0.0.0:11111/invoice-ocr 网页打不开

**Comment by guanshuicheng** [comment]
请使用 http://127.0.0.1:11111/invoice-ocr打开

**Comment by 15926273249** [comment]
就是用的这个网址，打不开


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"John"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月4日(星期四) 上午9:09
收件人:&nbsp;"guanshuicheng/invoice"<invoice@noreply.github.com&gt;;
抄送:&nbsp;"921825229"<921825229@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [guanshuicheng/invoice] 服务调用问题 (#18)





 
请使用 http://127.0.0.1:11111/invoice-ocr打开

**Comment by guanshuicheng** [comment]
这个项目没有做前端页面，请使用postman测试
