### ISSUE TITLE
如何改变http://127.0.0.1:1111/invoice-ocr中的ip和端口

### ISSUE THREAD

**Issue by Deeachain** [guanshuicheng/invoice#20]
* Running on http://0.0.0.0:1111/ (Press CTRL+C to quit)
运行app.py之后打开的服务，通过postman进行post请求http://127.0.0.1:1111/invoice-ocr，能够实现json输出。
请问我想把改变http://127.0.0.1:1111/invoice-ocr中的ip和端口，怎么该更改呢，我尝试过改变ip和端口，都不能发送请求

**Comment by guanshuicheng** [comment]
> * Running on http://0.0.0.0:1111/ (Press CTRL+C to quit)
>   运行app.py之后打开的服务，通过postman进行post请求[http://127.0.0.1:1111/invoice-ocr，能够实现json输出。](http://127.0.0.1:1111/invoice-ocr%EF%BC%8C%E8%83%BD%E5%A4%9F%E5%AE%9E%E7%8E%B0json%E8%BE%93%E5%87%BA%E3%80%82)
>   请问我想把改变[http://127.0.0.1:1111/invoice-ocr中的ip和端口，怎么该更改呢，我尝试过改变ip和端口，都不能发送请求](http://127.0.0.1:1111/invoice-ocr%E4%B8%AD%E7%9A%84ip%E5%92%8C%E7%AB%AF%E5%8F%A3%EF%BC%8C%E6%80%8E%E4%B9%88%E8%AF%A5%E6%9B%B4%E6%94%B9%E5%91%A2%EF%BC%8C%E6%88%91%E5%B0%9D%E8%AF%95%E8%BF%87%E6%94%B9%E5%8F%98ip%E5%92%8C%E7%AB%AF%E5%8F%A3%EF%BC%8C%E9%83%BD%E4%B8%8D%E8%83%BD%E5%8F%91%E9%80%81%E8%AF%B7%E6%B1%82)

请查看你的机器的当前的网段地址，127.0.0.1默认的是当前本地地址，端口号需要和你的机器暴露出来的端口号一致才能访问，建议在docker中操作部署。
