### ISSUE TITLE
yolo训练

### ISSUE THREAD

**Issue by simplew2011** [guanshuicheng/invoice#21]
您好，方便的话，能否给下您YOLO 文字检测的训练代码。Email：simplew2011@163.com

**Comment by guanshuicheng** [comment]
> 您好，方便的话，能否给下您YOLO 文字检测的训练代码。Email：[simplew2011@163.com](mailto:simplew2011@163.com)

检测的训练代码可以参考这个：`https://github.com/chineseocr/chineseocr/tree/master/train/text`

**Comment by guanshuicheng** [comment]
> 您好，方便的话，能否给下您YOLO 文字检测的训练代码。Email：[simplew2011@163.com](mailto:simplew2011@163.com)

检测的训练代码可以参考这个：[](https://github.com/chineseocr/chineseocr/tree/master/train/text)

**Comment by guanshuicheng** [comment]
> 您好，方便的话，能否给下您YOLO 文字检测的训练代码。Email：[simplew2011@163.com](mailto:simplew2011@163.com)

检测的训练代码可以参考这个：[https://github.com/chineseocr/chineseocr/tree/master/train/text](url)
