### ISSUE TITLE
Postman里是在Body的Key写file,Value选择图片吗，返回如下报错

### ISSUE THREAD

**Issue by hellomynameisq** [guanshuicheng/invoice#23]
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<HTML>
    <HEAD>
        <TITLE>Error Message</TITLE>
        <META http-equiv=Content-Type content="text/html; charset=UTF-8">
        <STYLE id=L_10060_1>A {
	FONT-WEIGHT: bold; FONT-SIZE: 10pt; COLOR: #005a80; FONT-FAMILY: tahoma
}
A:hover {
	FONT-WEIGHT: bold; FONT-SIZE: 10pt; COLOR: #0d3372; FONT-FAMILY: tahoma
}
TD {
	FONT-SIZE: 8pt; FONT-FAMILY: tahoma
}
TD.titleBorder {
	BORDER-RIGHT: #955319 1px solid; BORDER-TOP: #955319 1px solid; PADDING-LEFT: 8px; FONT-WEIGHT: bold; FONT-SIZE: 12pt; VERTICAL-ALIGN: middle; BORDER-LEFT: #955319 0px solid; COLOR: #955319; BORDER-BOTTOM: #955319 1px solid; FONT-FAMILY: tahoma; HEIGHT: 35px; BACKGROUND-COLOR: #d2b87a; TEXT-ALIGN: left
}
TD.titleBorderx {
	BORDER-RIGHT: #955319 0px solid; BORDER-TOP: #955319 1px solid; PADDING-LEFT: 8px; FONT-WEIGHT: bold; FONT-SIZE: 12pt; VERTICAL-ALIGN: middle; BORDER-LEFT: #955319 1px solid; COLOR: #978c79; BORDER-BOTTOM: #955319 1px solid; FONT-FAMILY: tahoma; HEIGHT: 35px; BACKGROUND-COLOR: #d2b87a; TEXT-ALIGN: left
}
.TitleDescription {
	FONT-WEIGHT: bold; FONT-SIZE: 12pt; COLOR: black; FONT-FAMILY: tahoma
}
SPAN.explain {
	FONT-WEIGHT: normal; FONT-SIZE: 10pt; COLOR: #934225
}
SPAN.TryThings {
	FONT-WEIGHT: normal; FONT-SIZE: 10pt; COLOR: #934225
}
.TryList {
	MARGIN-TOP: 5px; FONT-WEIGHT: normal; FONT-SIZE: 8pt; COLOR: black; FONT-FAMILY: tahoma
}
.X {
	BORDER-RIGHT: #955319 1px solid; BORDER-TOP: #955319 1px solid; FONT-WEIGHT: normal; FONT-SIZE: 12pt; BORDER-LEFT: #955319 1px solid; COLOR: #7b3807; BORDER-BOTTOM: #955319 1px solid; FONT-FAMILY: verdana; BACKGROUND-COLOR: #d1c2b4
}
.adminList {
	MARGIN-TOP: 2px
}
</STYLE>
        <META content="MSHTML 6.00.2800.1170" name=GENERATOR>
    </HEAD>
    <BODY bgColor=#f3f3ed>
        <TABLE cellSpacing=0 cellPadding=0 width="100%">
            <TBODY>
                <TR>
                    <TD class=titleBorderx width=30>
                        <TABLE height=25 cellSpacing=2 cellPadding=0 width=25 bgColor=black>
                            <TBODY>
                                <TR>
                                    <TD id=L_10060_x class=x valign=middle align=center>X</TD>
                                </TR>
                            </TBODY>
                        </TABLE>
                    </TD>
                    <TD class=titleBorder id=L_10060_2>Network Access Message:
                        <SPAN class=TitleDescription> The page cannot be displayed</SPAN>
                    </TD>
                </TR>
            </TBODY>
        </TABLE>
        <TABLE id=spacer>
            <TBODY>
                <TR>
                    <TD height=10></TD>
                </TR>
            </TBODY>
        </TABLE>
        <TABLE width=400>
            <TBODY>
                <TR>
                    <TD noWrap width=25></TD>
                    <TD width=400>
                        <SPAN class=explain>
                            <ID id=L_10060_3>
                                <B>Explanation:</B>
                            </ID>
                        </SPAN>
                        <ID id=L_10060_4> The request timed out before the page could be retrieved. </ID>
                        <BR>
                        <BR>
                        <B>
                            <SPAN class=tryThings>
                                <ID id=L_10060_5>
                                    <B>Try the following:</B>
                                </ID>
                            </SPAN>
                        </B>
                        <UL class=TryList>
                            <LI id=L_10060_6>
                                <B>Refresh page:</B> Search for the page again by clicking the Refresh button. The timeout may have occurred due to Internet congestion.
                                <LI id=L_10060_7>
                                    <B>Check spelling:</B> Check that you typed the Web page address correctly. The address may have been mistyped.
                                    <LI id=L_10060_8>
                                        <B>Contact website:</B> You may want to contact the website administrator to make sure the Web page still exists. You can do this by using the e-mail address or phone number listed on the website home page.
                                    </UL>
                                    <ID id=L_10060_9>If you are still not able to view the requested page, try contacting your administrator or Helpdesk.</ID>
                                    <BR>
                                    <BR>
    
                                </TD>
                            </TR>
                        </TBODY>
                    </TABLE>
                    <TABLE id=spacer>
                        <TBODY>
                            <TR>
                                <TD height=15></TD>
                            </TR>
                        </TBODY>
                    </TABLE>
                    <TABLE width=400>
                        <TBODY>
                            <TR>
                                <TD noWrap width=25></TD>
                                <TD width=400 id=L_10060_10>
                                    <B>Technical Information (for support personnel)</B>
                                    <UL class=adminList>
                                        <LI id=L_10060_11>Error Code 10060: Connection timeout

                                            <LI id=L_10060_12>Background: The gateway could not receive a timely response from the website you are trying to access. This might indicate that the network is congested, or that the website is experiencing technical difficulties.

                                                <LI id=L_10060_13>Date: 7/17/2020 7:59:50 AM [GMT]

                                                    <LI id=L_10060_14>Server: HKUTMPWV004.cn.asia.ad.pwcinternal.com

                                                        <LI id=L_10060_15>Source: Firewall

      
                                                        </UL>
                                                    </TD>
                                                </TR>
                                            </TBODY>
                                        </TABLE>
                                    </BODY>
                                </HTML>

**Comment by guanshuicheng** [comment]
> <TITLE>Error Message</TITLE> <STYLE id=L_10060_1>A { FONT-WEIGHT: bold; FONT-SIZE: 10pt; COLOR: #005a80; FONT-FAMILY: tahoma } A:hover { FONT-WEIGHT: bold; FONT-SIZE: 10pt; COLOR: #0d3372; FONT-FAMILY: tahoma } TD { FONT-SIZE: 8pt; FONT-FAMILY: tahoma } TD.titleBorder { BORDER-RIGHT: #955319 1px solid; BORDER-TOP: #955319 1px solid; PADDING-LEFT: 8px; FONT-WEIGHT: bold; FONT-SIZE: 12pt; VERTICAL-ALIGN: middle; BORDER-LEFT: #955319 0px solid; COLOR: #955319; BORDER-BOTTOM: #955319 1px solid; FONT-FAMILY: tahoma; HEIGHT: 35px; BACKGROUND-COLOR: #d2b87a; TEXT-ALIGN: left } TD.titleBorderx { BORDER-RIGHT: #955319 0px solid; BORDER-TOP: #955319 1px solid; PADDING-LEFT: 8px; FONT-WEIGHT: bold; FONT-SIZE: 12pt; VERTICAL-ALIGN: middle; BORDER-LEFT: #955319 1px solid; COLOR: #978c79; BORDER-BOTTOM: #955319 1px solid; FONT-FAMILY: tahoma; HEIGHT: 35px; BACKGROUND-COLOR: #d2b87a; TEXT-ALIGN: left } .TitleDescription { FONT-WEIGHT: bold; FONT-SIZE: 12pt; COLOR: black; FONT-FAMILY: tahoma } SPAN.explain { FONT-WEIGHT: normal; FONT-SIZE: 10pt; COLOR: #934225 } SPAN.TryThings { FONT-WEIGHT: normal; FONT-SIZE: 10pt; COLOR: #934225 } .TryList { MARGIN-TOP: 5px; FONT-WEIGHT: normal; FONT-SIZE: 8pt; COLOR: black; FONT-FAMILY: tahoma } .X { BORDER-RIGHT: #955319 1px solid; BORDER-TOP: #955319 1px solid; FONT-WEIGHT: normal; FONT-SIZE: 12pt; BORDER-LEFT: #955319 1px solid; COLOR: #7b3807; BORDER-BOTTOM: #955319 1px solid; FONT-FAMILY: verdana; BACKGROUND-COLOR: #d1c2b4 } .adminList { MARGIN-TOP: 2px } </STYLE>
> X	Network Access Message: The page cannot be displayed
> Explanation: The request timed out before the page could be retrieved.
> 
> Try the following:
> * Refresh page: Search for the page again by clicking the Refresh button. The timeout may have occurred due to Internet congestion.
> * Check spelling: Check that you typed the Web page address correctly. The address may have been mistyped.
> * Contact website: You may want to contact the website administrator to make sure the Web page still exists. You can do this by using the e-mail address or phone number listed on the website home page.
> 
> If you are still not able to view the requested page, try contacting your administrator or Helpdesk.
> 
> ```
>                             </TD>
>                         </TR>
>                     </TBODY>
>                 </TABLE>
>                 <TABLE id=spacer>
>                     <TBODY>
>                         <TR>
>                             <TD height=15></TD>
>                         </TR>
>                     </TBODY>
>                 </TABLE>
>                 <TABLE width=400>
>                     <TBODY>
>                         <TR>
>                             <TD noWrap width=25></TD>
>                             <TD width=400 id=L_10060_10>
>                                 <B>Technical Information (for support personnel)</B>
>                                 <UL class=adminList>
>                                     <LI id=L_10060_11>Error Code 10060: Connection timeout
> 
>                                         <LI id=L_10060_12>Background: The gateway could not receive a timely response from the website you are trying to access. This might indicate that the network is congested, or that the website is experiencing technical difficulties.
> 
>                                             <LI id=L_10060_13>Date: 7/17/2020 7:59:50 AM [GMT]
> 
>                                                 <LI id=L_10060_14>Server: HKUTMPWV004.cn.asia.ad.pwcinternal.com
> 
>                                                     <LI id=L_10060_15>Source: Firewall
> 
>   
>                                                     </UL>
>                                                 </TD>
>                                             </TR>
>                                         </TBODY>
>                                     </TABLE>
>                                 </BODY>
>                             </HTML>
> ```

**Comment by guanshuicheng** [comment]
> > <TITLE>Error Message</TITLE> <STYLE id=L_10060_1>A { FONT-WEIGHT: bold; FONT-SIZE: 10pt; COLOR: #005a80; FONT-FAMILY: tahoma } A:hover { FONT-WEIGHT: bold; FONT-SIZE: 10pt; COLOR: #0d3372; FONT-FAMILY: tahoma } TD { FONT-SIZE: 8pt; FONT-FAMILY: tahoma } TD.titleBorder { BORDER-RIGHT: #955319 1px solid; BORDER-TOP: #955319 1px solid; PADDING-LEFT: 8px; FONT-WEIGHT: bold; FONT-SIZE: 12pt; VERTICAL-ALIGN: middle; BORDER-LEFT: #955319 0px solid; COLOR: #955319; BORDER-BOTTOM: #955319 1px solid; FONT-FAMILY: tahoma; HEIGHT: 35px; BACKGROUND-COLOR: #d2b87a; TEXT-ALIGN: left } TD.titleBorderx { BORDER-RIGHT: #955319 0px solid; BORDER-TOP: #955319 1px solid; PADDING-LEFT: 8px; FONT-WEIGHT: bold; FONT-SIZE: 12pt; VERTICAL-ALIGN: middle; BORDER-LEFT: #955319 1px solid; COLOR: #978c79; BORDER-BOTTOM: #955319 1px solid; FONT-FAMILY: tahoma; HEIGHT: 35px; BACKGROUND-COLOR: #d2b87a; TEXT-ALIGN: left } .TitleDescription { FONT-WEIGHT: bold; FONT-SIZE: 12pt; COLOR: black; FONT-FAMILY: tahoma } SPAN.explain { FONT-WEIGHT: normal; FONT-SIZE: 10pt; COLOR: #934225 } SPAN.TryThings { FONT-WEIGHT: normal; FONT-SIZE: 10pt; COLOR: #934225 } .TryList { MARGIN-TOP: 5px; FONT-WEIGHT: normal; FONT-SIZE: 8pt; COLOR: black; FONT-FAMILY: tahoma } .X { BORDER-RIGHT: #955319 1px solid; BORDER-TOP: #955319 1px solid; FONT-WEIGHT: normal; FONT-SIZE: 12pt; BORDER-LEFT: #955319 1px solid; COLOR: #7b3807; BORDER-BOTTOM: #955319 1px solid; FONT-FAMILY: verdana; BACKGROUND-COLOR: #d1c2b4 } .adminList { MARGIN-TOP: 2px } </STYLE>
> > X	Network Access Message: The page cannot be displayed
> > Explanation: The request timed out before the page could be retrieved.
> > Try the following:
> > 
> > * Refresh page: Search for the page again by clicking the Refresh button. The timeout may have occurred due to Internet congestion.
> > * Check spelling: Check that you typed the Web page address correctly. The address may have been mistyped.
> > * Contact website: You may want to contact the website administrator to make sure the Web page still exists. You can do this by using the e-mail address or phone number listed on the website home page.
> > 
> > If you are still not able to view the requested page, try contacting your administrator or Helpdesk.
> > ```
> >                             </TD>
> >                         </TR>
> >                     </TBODY>
> >                 </TABLE>
> >                 <TABLE id=spacer>
> >                     <TBODY>
> >                         <TR>
> >                             <TD height=15></TD>
> >                         </TR>
> >                     </TBODY>
> >                 </TABLE>
> >                 <TABLE width=400>
> >                     <TBODY>
> >                         <TR>
> >                             <TD noWrap width=25></TD>
> >                             <TD width=400 id=L_10060_10>
> >                                 <B>Technical Information (for support personnel)</B>
> >                                 <UL class=adminList>
> >                                     <LI id=L_10060_11>Error Code 10060: Connection timeout
> > 
> >                                         <LI id=L_10060_12>Background: The gateway could not receive a timely response from the website you are trying to access. This might indicate that the network is congested, or that the website is experiencing technical difficulties.
> > 
> >                                             <LI id=L_10060_13>Date: 7/17/2020 7:59:50 AM [GMT]
> > 
> >                                                 <LI id=L_10060_14>Server: HKUTMPWV004.cn.asia.ad.pwcinternal.com
> > 
> >                                                     <LI id=L_10060_15>Source: Firewall
> > 
> >   
> >                                                     </UL>
> >                                                 </TD>
> >                                             </TR>
> >                                         </TBODY>
> >                                     </TABLE>
> >                                 </BODY>
> >                             </HTML>
> > ```

**Comment by guanshuicheng** [comment]
![Image text]( https://github.com/guanshuicheng/invoice/tree/master/test-invoice/use.png) ，可以参考这个，KEY框格中将type选择为file即可，value中上传本地图片

**Comment by hellomynameisq** [comment]
> ![Image text](https://github.com/guanshuicheng/invoice/tree/master/test-invoice/use.png) ，可以参考这个，KEY框格中将type选择为file即可，value中上传本地图片
嗯嗯，按您的说法，我搞定了！谢谢！
还有一个问题
返回值 金额的小数点有时会识别不出来，是需要进一步训练（用更大的数据集？）

**Comment by guanshuicheng** [comment]
> > ![Image text](https://github.com/guanshuicheng/invoice/tree/master/test-invoice/use.png) ，可以参考这个，KEY框格中将type选择为file即可，value中上传本地图片
> > 嗯嗯，按您的说法，我搞定了！谢谢！
> > 还有一个问题
> > 返回值 金额的小数点有时会识别不出来，是需要进一步训练（用更大的数据集？）

可以尝试构建语料库，微调CRNN模型，更新crnn目录下的key.py字典，增加需要训练的字符，可使用 [](https://github.com/Sanster/text_renderer ) 生成可训练数据集。

**Comment by guanshuicheng** [comment]
> > ![Image text](https://github.com/guanshuicheng/invoice/tree/master/test-invoice/use.png) ，可以参考这个，KEY框格中将type选择为file即可，value中上传本地图片
> > 嗯嗯，按您的说法，我搞定了！谢谢！
> > 还有一个问题
> > 返回值 金额的小数点有时会识别不出来，是需要进一步训练（用更大的数据集？）

可以尝试构建语料库，微调CRNN模型，更新crnn目录下的key.py字典，增加需要训练的字符，可使用https://github.com/Sanster/text_renderer生成可训练数据集。

**Comment by guanshuicheng** [comment]
> > ![Image text](https://github.com/guanshuicheng/invoice/tree/master/test-invoice/use.png) ，可以参考这个，KEY框格中将type选择为file即可，value中上传本地图片
> > 嗯嗯，按您的说法，我搞定了！谢谢！
> > 还有一个问题
> > 返回值 金额的小数点有时会识别不出来，是需要进一步训练（用更大的数据集？）

可以尝试构建语料库，微调CRNN模型，更新crnn目录下的key.py字典，增加需要训练的字符，可使用https://github.com/Sanster/text_renderer 生成可训练数据集。

**Comment by hellomynameisq** [comment]
> > > ![Image text](https://github.com/guanshuicheng/invoice/tree/master/test-invoice/use.png) ，可以参考这个，KEY框格中将type选择为file即可，value中上传本地图片
> > > 嗯嗯，按您的说法，我搞定了！谢谢！
> > > 还有一个问题
> > > 返回值 金额的小数点有时会识别不出来，是需要进一步训练（用更大的数据集？）
> 
> 可以尝试构建语料库，微调CRNN模型，更新crnn目录下的key.py字典，增加需要训练的字符，可使用https://github.com/Sanster/text_renderer 生成可训练数据集。

嗯嗯好的，感谢！
