### ISSUE TITLE
数据标注问题

### ISSUE THREAD

**Issue by LycsHub** [guanshuicheng/invoice#25]
您好,
        我使用您提供的YOLO3模型进行预测的时候,预测出的框如下图:
        ![example](https://gitee.com/tjdx1817054/typora/raw/master/example.jpg)     
        请问一下,在训练模型之前的数据标注阶段,是以发票什么部分作为YOLO3的目标进行检测?
        我翻看了其他issue中提到的 [chinese-ocr](https://github.com/chineseocr/chineseocr/tree/master/train/ocr),还是有些不太明白,可以具体的请教一下数据是如何标注的吗?

谢谢!

**Comment by guanshuicheng** [comment]
> 您好,
> 我使用您提供的YOLO3模型进行预测的时候,预测出的框如下图:
> ![example](https://camo.githubusercontent.com/575659758e91fde11c9de41833bd93c2c4c03ec8/68747470733a2f2f67697465652e636f6d2f746a6478313831373035342f7479706f72612f7261772f6d61737465722f6578616d706c652e6a7067)
> 请问一下,在训练模型之前的数据标注阶段,是以发票什么部分作为YOLO3的目标进行检测?
> 我翻看了其他issue中提到的 [chinese-ocr](https://github.com/chineseocr/chineseocr/tree/master/train/ocr),还是有些不太明白,可以具体的请教一下数据是如何标注的吗?
> 
> 谢谢!
标注的部分即推理的5个文字区域：发票代码、号码、开票日期，校验码和税后金额，本项目是借鉴的chineseocr，检测部分的详细demo可见chineseocr

**Comment by guanshuicheng** [comment]
> 您好,
> 我使用您提供的YOLO3模型进行预测的时候,预测出的框如下图:
> ![example](https://camo.githubusercontent.com/575659758e91fde11c9de41833bd93c2c4c03ec8/68747470733a2f2f67697465652e636f6d2f746a6478313831373035342f7479706f72612f7261772f6d61737465722f6578616d706c652e6a7067)
> 请问一下,在训练模型之前的数据标注阶段,是以发票什么部分作为YOLO3的目标进行检测?
> 我翻看了其他issue中提到的 [chinese-ocr](https://github.com/chineseocr/chineseocr/tree/master/train/ocr),还是有些不太明白,可以具体的请教一下数据是如何标注的吗?
> 
> 谢谢!

标注的部分即推理的5个文字区域：发票代码、号码、开票日期，校验码和税后金额，本项目是借鉴的chineseocr，检测部分的详细demo可见chineseocr
