### ISSUE TITLE
 You must feed a value for placeholder tensor 'Placeholder_368' with dtype float and shape [2]

### ISSUE THREAD

**Issue by simsq** [guanshuicheng/invoice#4]
![QQ截图20190823123817](https://user-images.githubusercontent.com/22512558/63567157-c27f3080-c5a2-11e9-9f33-03699801ff10.jpg)
这样算是跑起来了吗？还是怎么回事

**Comment by helloworld1973** [comment]
same error, how you fixed it?

**Comment by Spr1nt0a0** [comment]
same error, how you fixed it?

**Comment by Spr1nt0a0** [comment]
have you fixed it?

**Comment by xiaogogonuo** [comment]
refer to: https://www.cnblogs.com/sherrydatascience/p/13584237.html @Spr1nt0a0 @helloworld1973
